### ISSUE TITLE
comment synchroniser un projet avec le modele ?

### ISSUE THREAD

**Issue by gmembre-zenika** [Zenika/zenika-formation-framework#217] opened 2017-11-16 10:47 UTC
Je n'ai pas trouvé dans les wikis de zenika-formation-framework et Formation--Modele comment mettre à jour une formation déjà existante. 

Quelle est la procédure, quelle est la version à utiliser ?

**Comment by hgwood** [comment] 2017-11-16 11:42
I don't think there is any written procedure I'm afraid. What's generally done is to add the remote of the model to your repo, and cherry-pick or merge changes that you are interested in. It might be a bit tricky to figure out what commit to pick if your repo is far behind the model. You could try and find the last time your repo was sync'ed and rebase all commits from model/master that were made since that time.

**Comment by gmembre-zenika** [comment] 2017-11-16 13:19
not simple :)

could you please provide some examples and I'll add to the wiki ?

Thx

**Comment by hgwood** [comment] 2017-11-16 20:29
Sure. Could you give the name of the repo you want to update? I'll use it as an example, without actually updating it so that you can do it yourself afterwards.

**Comment by gmembre-zenika** [comment] 2017-11-16 22:05
Yep : formation-microservices-developpeurs

Thx !

**Comment by hgwood** [comment] 2017-11-21 13:24
Hi @gmembre-zenika 

I see that formation-microservices-developpeurs is already at framework version 2. So you be able to follow the framework [migration guide from v2 to v3](https://github.com/Zenika/zenika-formation-framework/blob/master/CHANGELOG.md#migrating) and you should be fine.

**Comment by jlandure** [comment] 2017-11-21 14:25
I handle it 👌

**Comment by jlandure** [comment] 2017-11-21 14:56
I think the following command to find the version in the package.json is not working on my laptop.
cat package.json
```
{
  "name": "formation-microservices-developpeurs",
  "description": "Formation Microservices Developpeurs",
  "version": "0.0.1",
  "author": "Zenika",
  "homepage": "http://zenika.com/formation-microservices-developpeurs.html",
  "repository": {
    "type": "git",
    "url": "https://github.com/Zenika/formation-microservices-developpeurs.git"
  },
  "private": true,
  "dependencies": {
    "grunt": "^0.4.5",
    "gulp": "^3.9.0",
    "zenika-formation-framework": "^3.0.0"
  },
  "scripts": {
    "start": "grunt",
    "deploy": "zenika-formation-deploy"
  }
}
```
`cat package.json | sed -n -e '/"zenika-formation-framework":/ s/.*"\^\([0-9]\+\).*".*/\1/p'` show nothing.
So the docker image used is the `latest` (5 months old).

**Comment by hgwood** [comment] 2017-11-21 22:59
I've triggered a new build of the docker image so that `latest`==`v3.1.0`.

**Comment by hgwood** [comment] 2017-11-21 23:02
@jlandure the command you give works fine on the `package.json` you give on my machine. I'm confused.

**Comment by looztra** [comment] 2018-01-11 10:34
It looks like a duplicate of #212  no?

**Comment by hgwood** [comment] 2018-01-11 11:18
Well not quite because #212 is about automating the updating, while this one is about how to do it right now without automation. This issue has been answered and should be closed. The problem about the regex and `package.json` raised by @jlandure should have its own issue.

**Closed by hgwood** 2018-01-11 11:18 UTC
